name: WordPress CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.4'
    - name: Update composer
      run: composer update
    - name: Install dependencies
      run: composer install
    - name: Run tests
      run: vendor/bin/phpunit tests/